// <auto-generated />
using System;
using GdeOni.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GdeOni.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320101732_SearchKeyForDeceased")]
    partial class SearchKeyForDeceased
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.Deceased", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("search_key");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("short_description");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_deceaseds");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_deceased_created_at_utc");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_deceased_created_by_user_id");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_deceased_is_verified");

                    b.HasIndex("SearchKey")
                        .IsUnique()
                        .HasDatabaseName("ux_deceased_search_key");

                    b.ToTable("deceaseds", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.DeceasedMemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("author_display_name");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("deceased_id")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.HasKey("Id")
                        .HasName("pk_deceased_memory_entries");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_memory_entries_author_user_id");

                    b.HasIndex("deceased_id")
                        .HasDatabaseName("ix_memory_entries_deceased_id");

                    b.ToTable("deceased_memory_entries", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.DeceasedPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.Property<Guid>("deceased_id")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.HasKey("Id")
                        .HasName("pk_deceased_photos");

                    b.HasIndex("AddedByUserId")
                        .HasDatabaseName("ix_deceased_photos_added_by_user_id");

                    b.HasIndex("deceased_id")
                        .HasDatabaseName("ix_deceased_photos_deceased_id");

                    b.ToTable("deceased_photos", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.TrackedDeceased", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<bool>("NotifyOnBirthAnniversary")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_birth_anniversary");

                    b.Property<bool>("NotifyOnDeathAnniversary")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_death_anniversary");

                    b.Property<string>("PersonalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("personal_notes");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TrackedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tracked_at_utc");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tracked_deceased");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_tracked_deceased_deceased_id");

                    b.HasIndex("user_id")
                        .HasDatabaseName("ix_tracked_deceased_user_id");

                    b.HasIndex("user_id", "DeceasedId")
                        .IsUnique()
                        .HasDatabaseName("ux_tracked_deceased_user_id_deceased_id");

                    b.ToTable("tracked_deceased", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.Deceased", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceaseds_users_created_by_user_id");

                    b.OwnsOne("GdeOni.Domain.Aggregates.Deceased.BurialLocation", "BurialLocation", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Accuracy")
                                .HasColumnType("integer")
                                .HasColumnName("location_accuracy");

                            b1.Property<string>("CemeteryName")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("cemetery_name");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("country");

                            b1.Property<string>("GraveNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("grave_number");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("PlotNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("plot_number");

                            b1.Property<string>("Region")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("region");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceaseds");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceaseds_deceaseds_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.Deceased.DeceasedMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AdditionalInfo")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("metadata_additional_info");

                            b1.Property<string>("Epitaph")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("metadata_epitaph");

                            b1.Property<bool>("IsMilitaryService")
                                .HasColumnType("boolean")
                                .HasColumnName("metadata_is_military_service");

                            b1.Property<string>("Religion")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("metadata_religion");

                            b1.Property<string>("Source")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("metadata_source");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceaseds");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceaseds_deceaseds_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.Deceased.LifePeriod", "LifePeriod", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("birth_date");

                            b1.Property<DateTime>("DeathDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("death_date");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceaseds");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceaseds_deceaseds_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.Deceased.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("middle_name");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceaseds");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceaseds_deceaseds_id");
                        });

                    b.Navigation("BurialLocation")
                        .IsRequired();

                    b.Navigation("LifePeriod")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.DeceasedMemoryEntry", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deceased_memory_entries_users_author_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.Deceased.Deceased", null)
                        .WithMany("Memories")
                        .HasForeignKey("deceased_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_memory_entries_deceaseds_deceased_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.DeceasedPhoto", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_photos_users_added_by_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.Deceased.Deceased", null)
                        .WithMany("Photos")
                        .HasForeignKey("deceased_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_photos_deceaseds_deceased_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.TrackedDeceased", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.Deceased.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_deceased_deceaseds_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany("TrackedDeceasedItems")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_deceased_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Deceased.Deceased", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.User", b =>
                {
                    b.Navigation("TrackedDeceasedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
