// <auto-generated />
using System;
using GdeOni.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GdeOni.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_from_ip");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid?>("MainMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_media_id");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("search_key");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("short_description");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_deceased_records");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_deceased_created_at_utc");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_deceased_created_by_user_id");

                    b.HasIndex("IsVerified")
                        .HasDatabaseName("ix_deceased_is_verified");

                    b.HasIndex("MainMediaId")
                        .HasDatabaseName("ix_deceased_main_media_id");

                    b.HasIndex("SearchKey")
                        .IsUnique()
                        .HasDatabaseName("ux_deceased_search_key");

                    b.ToTable("deceased_records", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedEdit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<DateTime>("EditedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at_utc");

                    b.Property<Guid?>("EditedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by_user_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_deceased_edits");

                    b.HasIndex("EditedByUserId")
                        .HasDatabaseName("ix_deceased_edits_edited_by_user_id");

                    b.HasIndex("DeceasedId", "EditedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_deceased_edits_deceased_id_edited_at_utc");

                    b.ToTable("deceased_edits", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMainPhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_photo");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_status");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_deceased_media");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_deceased_media_deceased_id");

                    b.HasIndex("ModerationStatus")
                        .HasDatabaseName("ix_deceased_media_moderation_status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_deceased_media_storage_key");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_deceased_media_uploaded_by_user_id");

                    b.ToTable("deceased_media", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("deceased_id")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.HasKey("Id")
                        .HasName("pk_deceased_memory_entries");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_memory_entries_author_user_id");

                    b.HasIndex("deceased_id", "ModerationStatus")
                        .HasDatabaseName("ix_memory_entries_deceased_id_moderation_status");

                    b.ToTable("deceased_memory_entries", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Events.CustomEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("LeadDaysCsv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lead_days");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_custom_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_custom_events_user_id");

                    b.ToTable("custom_events", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Events.HolidayReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HolidayKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("holiday_key");

                    b.Property<string>("LeadDaysCsv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lead_days");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_holiday_reminders");

                    b.HasIndex("UserId", "HolidayKey")
                        .IsUnique()
                        .HasDatabaseName("ux_holiday_reminders_user_id_holiday_key");

                    b.ToTable("holiday_reminders", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_recipient_user_id_is_read_created_at_utc");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<DateTime>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at_utc");

                    b.Property<Guid>("ParticipantAId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_a_id");

                    b.Property<Guid>("ParticipantBId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_b_id");

                    b.HasKey("Id")
                        .HasName("pk_relative_conversations");

                    b.HasIndex("LastMessageAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_relative_conversations_last_message_at_utc");

                    b.HasIndex("ParticipantAId")
                        .HasDatabaseName("ix_relative_conversations_participant_a_id");

                    b.HasIndex("ParticipantBId")
                        .HasDatabaseName("ix_relative_conversations_participant_b_id");

                    b.HasIndex("DeceasedId", "ParticipantAId", "ParticipantBId")
                        .IsUnique()
                        .HasDatabaseName("ux_relative_conversations_deceased_a_b");

                    b.ToTable("relative_conversations", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTime?>("EditedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_relative_messages");

                    b.HasIndex("ConversationId", "CreatedAtUtc")
                        .HasDatabaseName("ix_relative_messages_conversation_created");

                    b.ToTable("relative_messages", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_user_id");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_relative_reports");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_relative_reports_deceased_id");

                    b.HasIndex("ReportedUserId")
                        .HasDatabaseName("ix_relative_reports_reported_user_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_relative_reports_status_created_at_utc");

                    b.HasIndex("ReporterUserId", "ReportedUserId", "ConversationId")
                        .HasDatabaseName("ix_relative_reports_reporter_user_id_reported_user_id_conversa");

                    b.ToTable("relative_reports", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Sharing.ShareBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid[]>("DeceasedIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("deceased_ids");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_share_bundles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_share_bundles_code");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_share_bundles_created_by_user_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_share_bundles_expires_at_utc");

                    b.ToTable("share_bundles", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Subscriptions.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountRub")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_rub");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalPaymentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_payment_id");

                    b.Property<DateTime?>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end_utc");

                    b.Property<DateTime?>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start_utc");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription_payments");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_subscription_payments_created_at_utc");

                    b.HasIndex("ExternalPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_payments_external_payment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscription_payments_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscription_payments_user_id");

                    b.ToTable("subscription_payments", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AcceptedByUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("accepted_by_user");

                    b.Property<DateTime?>("AcceptedByUserAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_by_user_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("LastUserReply")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_user_reply");

                    b.Property<DateTime?>("LastUserReplyAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_user_reply_at_utc");

                    b.Property<int>("ReopenedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reopened_count");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_support_tickets");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_support_tickets_created_at_utc");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_support_tickets_kind");

                    b.HasIndex("ResolvedByUserId")
                        .HasDatabaseName("ix_support_tickets_resolved_by_user_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_support_tickets_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_support_tickets_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_support_tickets_user_id");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_attachments");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_support_ticket_attachments_storage_key");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_support_ticket_attachments_ticket_id");

                    b.ToTable("support_ticket_attachments", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author_kind");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_messages");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_support_ticket_messages_author_user_id");

                    b.HasIndex("TicketId", "CreatedAtUtc")
                        .HasDatabaseName("ix_support_ticket_messages_ticket_id_created_at");

                    b.ToTable("support_ticket_messages", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.TrackedDeceased", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BirthAnniversaryLeadDaysCsv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("birth_anniversary_lead_days");

                    b.Property<string>("DeathAnniversaryLeadDaysCsv")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("death_anniversary_lead_days");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<string>("PersonalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("personal_notes");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TrackedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tracked_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tracked_deceased");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_tracked_deceased_deceased_id");

                    b.HasIndex("user_id", "DeceasedId")
                        .IsUnique()
                        .HasDatabaseName("ux_tracked_deceased_user_id_deceased_id");

                    b.ToTable("tracked_deceased", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowRelativeConnections")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_relative_connections");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at_utc");

                    b.Property<Guid?>("BlockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_by_user_id");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blocked_reason");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("ComplimentaryAccessGrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complimentary_access_granted_at_utc");

                    b.Property<Guid?>("ComplimentaryAccessGrantedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("complimentary_access_granted_by_admin_id");

                    b.Property<string>("ComplimentaryAccessNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("complimentary_access_note");

                    b.Property<DateTime?>("ComplimentaryAccessUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complimentary_access_until_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmationRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmation_required");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmation_token_expires_at_utc");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("email_confirmation_token_hash");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at_utc");

                    b.Property<string>("FullName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_confirmed");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expires_at_utc");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password_reset_token_hash");

                    b.Property<DateTime?>("PrivacyPolicyAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("privacy_policy_accepted_at_utc");

                    b.Property<int>("PrivacyPolicyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("privacy_policy_version");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("TermsAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at_utc");

                    b.Property<int>("TermsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("terms_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserNameNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name_normalized");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BlockedByUserId")
                        .HasDatabaseName("ix_users_blocked_by_user_id");

                    b.HasIndex("ComplimentaryAccessGrantedByAdminId")
                        .HasDatabaseName("ix_users_complimentary_access_granted_by_admin_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("EmailConfirmationTokenHash")
                        .HasDatabaseName("ix_users_email_confirmation_token_hash")
                        .HasFilter("email_confirmation_token_hash IS NOT NULL");

                    b.HasIndex("IsBlocked")
                        .HasDatabaseName("ix_users_is_blocked")
                        .HasFilter("is_blocked = true");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ux_users_login");

                    b.HasIndex("PasswordResetTokenHash")
                        .HasDatabaseName("ix_users_password_reset_token_hash")
                        .HasFilter("password_reset_token_hash IS NOT NULL");

                    b.HasIndex("RegisteredAtUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_users_registered_at_utc");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Notifications.Push.PushSubscriptionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at_utc");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ux_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Notifications.SentAnniversaryEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AnniversaryDate")
                        .HasColumnType("date")
                        .HasColumnName("anniversary_date");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sent_anniversary_emails");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_sent_anniversary_emails_deceased_id");

                    b.HasIndex("UserId", "DeceasedId", "Kind", "AnniversaryDate")
                        .IsUnique()
                        .HasDatabaseName("ux_sent_anniversary_emails_user_deceased_kind_date");

                    b.ToTable("sent_anniversary_emails", (string)null);
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Relatives.RelativeDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeceasedId")
                        .HasColumnType("uuid")
                        .HasColumnName("deceased_id");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("RelativeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("relative_user_id");

                    b.HasKey("Id")
                        .HasName("pk_relative_discoveries");

                    b.HasIndex("DeceasedId")
                        .HasDatabaseName("ix_relative_discoveries_deceased_id");

                    b.HasIndex("RelativeUserId")
                        .HasDatabaseName("ix_relative_discoveries_relative_user_id");

                    b.HasIndex("OwnerUserId", "IsNew")
                        .HasDatabaseName("ix_relative_discoveries_owner_user_id_is_new");

                    b.HasIndex("OwnerUserId", "DeceasedId", "RelativeUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_relative_discoveries_owner_deceased_relative");

                    b.ToTable("relative_discoveries", (string)null);
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Auth.RefreshToken", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_records_users_created_by_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMedia", "MainMedia")
                        .WithMany()
                        .HasForeignKey("MainMediaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deceased_records_deceased_media_main_media_id");

                    b.OwnsOne("GdeOni.Domain.Aggregates.DeceasedRecords.BurialLocation", "BurialLocation", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Accuracy")
                                .HasColumnType("integer")
                                .HasColumnName("location_accuracy");

                            b1.Property<double?>("AccuracyMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("accuracy_meters");

                            b1.Property<string>("CemeteryName")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("cemetery_name");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("country");

                            b1.Property<string>("GraveNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("grave_number");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("PlotNumber")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("plot_number");

                            b1.Property<string>("Region")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("region");

                            b1.HasKey("DeceasedId");

                            b1.HasIndex("Latitude", "Longitude")
                                .HasDatabaseName("ix_deceased_burial_lat_lon");

                            b1.ToTable("deceased_records");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceased_records_deceased_records_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AdditionalInfo")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Epitaph")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Religion")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Source")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceased_records");

                            b1.ToJson("Metadata");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceased_records_deceased_records_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.DeceasedRecords.LifePeriod", "LifePeriod", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly?>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.Property<DateOnly>("DeathDate")
                                .HasColumnType("date")
                                .HasColumnName("death_date");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceased_records");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceased_records_deceased_records_id");
                        });

                    b.OwnsOne("GdeOni.Domain.Aggregates.DeceasedRecords.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeceasedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("middle_name");

                            b1.HasKey("DeceasedId");

                            b1.ToTable("deceased_records");

                            b1.WithOwner()
                                .HasForeignKey("DeceasedId")
                                .HasConstraintName("fk_deceased_records_deceased_records_id");
                        });

                    b.Navigation("BurialLocation");

                    b.Navigation("LifePeriod")
                        .IsRequired();

                    b.Navigation("MainMedia");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedEdit", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany("Edits")
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_edits_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("EditedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deceased_edits_users_edited_by_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMedia", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany("Media")
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_media_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_media_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.DeceasedMemoryEntry", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deceased_memory_entries_users_author_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany("Memories")
                        .HasForeignKey("deceased_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deceased_memory_entries_deceased_records_deceased_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Events.CustomEvent", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_events_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Events.HolidayReminder", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_reminders_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Notifications.Notification", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeConversation", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_conversations_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_conversations_users_participant_a_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_conversations_users_participant_b_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeMessage", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.Relatives.RelativeConversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_messages_relative_conversations_conversation_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeReport", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_reports_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_reports_users_reported_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_reports_users_reporter_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Sharing.ShareBundle", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_share_bundles_users_created_by_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicket", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_support_tickets_users_resolved_by_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_support_tickets_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicketAttachment", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.Support.SupportTicket", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_ticket_attachments_support_tickets_ticket_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicketMessage", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_support_ticket_messages_users_author_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.Support.SupportTicket", null)
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_ticket_messages_support_tickets_ticket_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.TrackedDeceased", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_deceased_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany("TrackedDeceasedItems")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracked_deceased_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.User", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("BlockedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_users_blocked_by_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("ComplimentaryAccessGrantedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_users_complimentary_access_granted_by_admin_id");

                    b.OwnsOne("GdeOni.Domain.Aggregates.User.Subscription", "Subscription", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CancelledAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_cancelled_at_utc");

                            b1.Property<DateTime?>("CurrentPeriodStartedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_current_period_started_at_utc");

                            b1.Property<DateTime?>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("subscription_expires_at_utc");

                            b1.Property<string>("LastPaymentId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("subscription_last_payment_id");

                            b1.Property<string>("Plan")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("subscription_plan");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("subscription_status");

                            b1.HasKey("UserId");

                            b1.HasIndex("ExpiresAtUtc")
                                .HasDatabaseName("ix_users_subscription_expires_at_utc");

                            b1.HasIndex("LastPaymentId")
                                .HasDatabaseName("ix_users_subscription_last_payment_id");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Subscription")
                        .IsRequired();
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Notifications.Push.PushSubscriptionRecord", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Notifications.SentAnniversaryEmail", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sent_anniversary_emails_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sent_anniversary_emails_users_user_id");
                });

            modelBuilder.Entity("GdeOni.Infrastructure.Relatives.RelativeDiscovery", b =>
                {
                    b.HasOne("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", null)
                        .WithMany()
                        .HasForeignKey("DeceasedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_discoveries_deceased_records_deceased_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_discoveries_users_owner_user_id");

                    b.HasOne("GdeOni.Domain.Aggregates.User.User", null)
                        .WithMany()
                        .HasForeignKey("RelativeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relative_discoveries_users_relative_user_id");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.DeceasedRecords.Deceased", b =>
                {
                    b.Navigation("Edits");

                    b.Navigation("Media");

                    b.Navigation("Memories");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Relatives.RelativeConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.Support.SupportTicket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GdeOni.Domain.Aggregates.User.User", b =>
                {
                    b.Navigation("TrackedDeceasedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
